# Generated by Django 5.0.3 on 2024-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag nomi')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Taglar',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Saytga chiqarish'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='Bannerga chiqarish'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Haftalik yangilk'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Kurishlar soni'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='main.tags', verbose_name='Taglar'),
        ),
    ]
